Beer and bear.
urfu-2017/markup-task-3 pull request #18
Opened 2017-10-21 20:14 UTC by Damirikys

Let's go.

2017-10-21 20:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 07:41 UTC, vaseker reviewed
Нужны уточнения. 
В целом весело-задорно по идее и реализации.

2017-10-23 07:41 UTC, vaseker commented on index.css
> +    background: url('yellow-wall.jpg');
background-image тогда уж

2017-10-23 07:41 UTC, vaseker commented on index.css
> +    border-top: 2px dashed;
тут не стоит полагаться на default color #000, лучше указать цвет явно

2017-10-23 07:41 UTC, vaseker commented on index.css
> +    filter: grayscale(70%);
![wooow](https://user-images.githubusercontent.com/1942271/31877009-4a02d828-b7ee-11e7-920b-b59f4c881cc0.jpg)

2017-10-23 07:41 UTC, vaseker commented on index.css
> +    height: 100%;
для ячейки это бессмысленно. ячейка таблицы подстраивается под высоту строки

2017-10-23 07:41 UTC, vaseker commented on index.html
> +                        Се&shy;го&shy;дня с утра рос&shy;сий&shy;ский по&shy;ли&shy;ти&shy;че&shy;ский
омагад. тут принципиально не используется css-свойство word-break? или тут критически нужны правильные переносы?

2017-10-23 07:41 UTC, vaseker commented on index.html
> +                        <img src="hourse.jpg" alt="Собчак">
ho~~u~~rse

2017-10-24 08:08 UTC, vaseker requested changes
🍅

2017-10-25 07:23 UTC, Damirikys commented on index.html
> +                        Се&shy;го&shy;дня с утра рос&shy;сий&shy;ский по&shy;ли&shy;ти&shy;че&shy;ский
На лекции было сказано сделать мягкие и дали ссылку на сервис, который их расставляет.

2017-10-25 07:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-25 07:24 UTC, Damirikys commented on index.css
> +    border-top: 2px dashed;
поставил border-color: #000

2017-10-25 07:44 UTC, vaseker commented
🍏

2017-10-25 07:44 UTC, closed without merging