Мелкозёров Леонид
urfu-2017/markup-task-3 pull request #24
Opened 2017-10-22 12:59 UTC by danmerus

2017-10-22 12:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 06:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-08 09:51 UTC, dotokoto requested changes
Оформление прикольное, но надо переверстать с таблиц на `column-count`. И не все требования задания выполнены:
- не вижу вертикального текста
- нет картинок на несколько колонок
- нет выделения первой буквы первого параграфа
- нет переносов в тексте

И снизу слева торчит странная длинная колонка, надо ее тоже вписать в общий макет. Чтобы все колонки были одной высоты

2017-11-08 09:51 UTC, Dotokoto commented on index.css
> +    src: url(10763.otf) format('truetype');
В современных браузерах используются в основном шрифты в форматах woff и woff2. Было бы круто, если бы у тебя использовались и более современные форматы, а не только ttf

2017-11-08 09:51 UTC, Dotokoto commented on index.css
> +    src: url(10763.otf) format('truetype');
И не хватает локального подключения шрифта `local('The Capt')` например. Чтобы у пользователей, у которых этот шрифт установлен на компьютере, он не загружался зря

2017-11-08 09:51 UTC, Dotokoto commented on index.css
> +    padding-left: 20pt;
Почему ты решил все размеры задавать в `pt`? Они в вебе как раз практически не используются, в отличие от px/em

2017-11-08 09:51 UTC, Dotokoto commented on index.html
> +    <table >
Почему у тебя газета сверстана через таблицу? На лекции должны были рассказывать про `column-count`. В задаче предполагалась многоколоночная верстка с помощью этого свойства, а не с помощью таблиц

2017-11-08 09:51 UTC, Dotokoto commented on index.html
> +                готовности неуклонно двигаться впередѣ по пути своихѣ отдаленныхѣ в ближайшихѣ цѣлей.
В описании задания есть требование об использовании переносов, у тебя в тексте их не хватает. Можно найти автоматические расставлялки переносов, и прогнать весь текст через них.

2017-11-08 09:51 UTC, Dotokoto commented
:tomato:

2017-11-11 11:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-11 11:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-11 11:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-13 10:45 UTC, dotokoto approved these changes
Прикольно сделал рамки! Правда, у этого способа есть недостаток - при изменении размеров экрана рамка может расползаться на несколько колонок. 
Написала еще пару замечаний по коду. Править уже не буду заставлять, но прочитай и прими к сведению )

2017-11-13 10:45 UTC, Dotokoto commented on index.css
> +.bigTable
В css не принято использовать camelCase, лучше написать `big-table`

2017-11-13 10:45 UTC, Dotokoto commented on index.css
> +    font-family: 'AA American Captain';
Принято задавать несколько шрифтов, на случай, если главный не подгрузится. Вторым шрифтом нужно задать какой-нибудь системный безопасный шрифт (их список можно найти здесь: https://www.w3schools.com/cssref/css_websafe_fonts.asp). Или даже несколько безопасных шрифто. И в конце указывать семейство шрифтов (serif/sans-serif/и тд, в зависимости от семейста твоего главного шрифта).
То есть должно получится что-то такое: 
`font-family: 'AA American Captain', Impact, Charcoal, sans-serif`

2017-11-13 10:45 UTC, closed without merging