shit newspaper
urfu-2017/markup-task-3 pull request #26
Opened 2017-10-22 15:06 UTC by Admirallll

2017-10-22 15:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 07:03 UTC, VasiliiKuznecov commented
Привет, я сейчас переназначу тебе ментора, это нормально

2017-10-26 07:03 UTC, VasiliiKuznecov commented
:bell:

2017-10-26 07:05 UTC, Admirallll commented
А что случилось с предыдущим?

2017-10-26 07:26 UTC, VasiliiKuznecov commented
Он попросил снизить нагрузку по задачам

2017-10-30 15:11 UTC, savichev-igor requested changes
В целом ок, но к сожалению соблюдены не все особенности вёрстки того времени и газета уж какая-то слишком простая вышла..

:tomato:

2017-10-30 15:11 UTC, Savichev-Igor commented on index.css
> +    column-count: 2;
А вендорные префиксы?

Вдруг откроют в старом браузере

2017-10-30 15:11 UTC, Savichev-Igor commented on index.css
> +
Лишняя строка

2017-10-30 15:11 UTC, Savichev-Igor commented on index.css
> +    margin-top: 2px;
Можно сделать в одно правило: `margin: 2px 0 0;`

2017-10-30 15:11 UTC, Savichev-Igor commented on index.html
> +        <div class="description">Выпуск от 29 июля, 1985</div>
Сейчас в HTML5 стало так много семантических тэгов, что `div` уже практически можно не использовать

Не искал никакого подходящего тэга?

2017-10-30 15:11 UTC, Savichev-Igor commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">
Давай ещё попробуем сами подключить шрифт с использованием `local` и кучи форматов)?

2017-10-30 17:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 09:38 UTC, Savichev-Igor commented on index.css
> +    column-count: 3;
Обычно принято указывать сначала вендорные, а в самом конце обычные

2017-10-31 09:39 UTC, Savichev-Igor commented on index.html
> +        <div class="news">
`section`?

2017-10-31 09:40 UTC, savichev-igor approved these changes

2017-10-31 09:40 UTC, Savichev-Igor commented
⭐️

2017-10-31 09:40 UTC, closed without merging