сверстал газету
urfu-2017/markup-task-3 pull request #34
Opened 2017-10-22 22:25 UTC by Edheltur

Марти, это не тот 17й!
[Дизайн](https://cdnimg.rg.ru/img/content/140/77/73/y_d_850.jpg)

2017-10-22 22:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 16:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-27 06:56 UTC, Vittly requested changes
прикольно! но давай немного улучшим
🍅

2017-10-27 06:56 UTC, Vittly commented on css/blocks/main-visual.css
> +    src: url(../../fonts/kanonnik.ttf);
кмк еще нужен woff - он современнее и поддержка более "зеленая" (can i use)

сразу про [баг на узком экране](https://yadi.sk/i/dDT0z_5v3P8xim)

2017-10-27 06:56 UTC, Vittly commented on css/blocks/main-visual.css
> +    src: url(../../fonts/kanonnik.ttf);
при переключении режимов не понятно, какой из них сейчас активен. Да, можно посмотреть на эффект в случае большой/маленький шрифт, но понятия "хроший шрифт" и "плохой шрифт" довольно относительны

2017-10-27 06:56 UTC, Vittly commented on css/blocks/main-visual.css
> +    left: calc(50% - 320px);
calc-и не очень хороши, можно сделать без явных пикселей?

2017-10-27 06:56 UTC, Vittly commented on css/blocks/main-visual.css
> +    left: calc(50% - 320px);
тем более, что фишка с относительной позицией "сразу за буковой У" обломался на узких экранах. Лучше тогда из даты и титула сделать один элемент, чтобы он целиком передвигался по экрану, не разбивая композиции

2017-10-27 06:56 UTC, Vittly commented on css/blocks/main-visual.css
> +    left: calc(50% - 320px);
может проще всего сделать разные стили через media-query, а то у тебя долвльно сложная задумка

2017-10-27 06:56 UTC, Vittly commented on css/blocks/settings.css
> +
лишняя пустая строка

2017-10-27 06:56 UTC, Vittly commented on css/blocks/settings.css
> +    margin-left: .3rem;
`margin: 0 .3rem`

2017-10-27 06:56 UTC, Vittly commented on css/blocks/settings.css
> +    padding: .5rem;
лучше высоту через `line-height` сделать или делать из них `inline-block`-и, а то сейчас размеры [довольно странно считаются](https://yadi.sk/i/UhrGRcdJ3P8yaU)

2017-10-27 06:56 UTC, Vittly commented on css/blocks/subscribe.css
> +    column-rule: #373737;
зачем эта строка?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    text-align: center;
хм немного странное решение

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    font-family: Chekhovskoy, serif;
почему не унес выше?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +input[id='font-bad']:checked ~ main
правила про применение опций я бы в отдельный файл положил

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    filter: contrast(300%) brightness(70%) sepia(100%);
а вендор-префиксы?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    margin: 0 .2rem .1rem 0;
padding/margin/fload буквы? Это точно все работает? и зачем так сложно?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    filter: contrast(200%) brightness(110%);
вендор-префиксы

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    text-align: justify;
советую еще правило `column-fill`

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    column-count: 2;
здесь лучше задать `column-width`, чтобы не получались слишком узкие столбики

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    display: none;
можно в setting унести

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    border-color: #653c00;
это отбилось от группы

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    content: ' ';
?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    display: block;
он и так блочный

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    border: none;
?

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    border-color: #373737;
? ниже же перечислены

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    padding: 1rem;
на макете сверху отступ больше

2017-10-27 06:56 UTC, Vittly commented on css/pages/index.css
> +    break-before: auto;
можешь расписать зачем свойства `break-*` ?

2017-10-27 06:56 UTC, Vittly commented on index.html
> +
лишняя строка

2017-10-27 06:56 UTC, Vittly commented on index.html
> +<input type="radio" id="size-big" name="size">
я бы их унес прямо в `.settings`

2017-10-27 06:56 UTC, Vittly commented on index.html
> +    </div>
за БЭМ плюсик, но не выдержал ты нейминг ниже заголовка)

2017-10-27 06:56 UTC, Vittly commented on index.html
> +</main>
на дизайне нет футера, но я бы сделал

2017-10-29 10:08 UTC, Edheltur commented on css/blocks/settings.css
> +    margin-left: .3rem;
👍

2017-10-29 10:08 UTC, Edheltur commented on css/blocks/settings.css
> +
👍

2017-10-29 10:09 UTC, Edheltur commented on css/blocks/subscribe.css
> +    column-rule: #373737;
Сначала делал разделители. потом выпилил.
👍

2017-10-29 10:30 UTC, Edheltur commented on css/pages/index.css
> +    content: ' ';
👍

2017-10-29 10:30 UTC, Edheltur commented on css/pages/index.css
> +    display: block;
👍

2017-10-29 10:30 UTC, Edheltur commented on css/pages/index.css
> +    border-color: #653c00;
👍

2017-10-29 10:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 10:40 UTC, Edheltur commented on css/pages/index.css
> +    filter: contrast(300%) brightness(70%) sepia(100%);
Зачем засорять код если есть autoprefixer? Да и фильтр довольно зеленую поддержку имеет.

2017-10-29 10:41 UTC, Edheltur commented on css/pages/index.css
> +    break-before: auto;
Чтобы не было висящих заголовков. Хотя почему-то все равно иногда получается что текст перезжает на следующую от заголовка колонку.

2017-10-29 10:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 10:54 UTC, Edheltur commented on css/pages/index.css
> +    margin: 0 .2rem .1rem 0;
padding/margin - это я упоролся, верно. 
Но float нужен, без него не будет эффекта буквицы.
![с float: left](https://user-images.githubusercontent.com/4038984/32142851-52663ae6-bcc1-11e7-88ae-d88c5f772085.png)
![без float: left](https://user-images.githubusercontent.com/4038984/32142853-569e3924-bcc1-11e7-8760-a44c36f854c9.png)

2017-10-29 10:57 UTC, Edheltur commented on css/pages/index.css
> +input[id='font-bad']:checked ~ main
👍

2017-10-29 10:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 11:06 UTC, Edheltur commented on css/pages/index.css
> +    padding: 1rem;
👍

2017-10-30 15:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-30 15:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 16:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 16:31 UTC, Edheltur commented on css/blocks/main-visual.css
> +    src: url(../../fonts/kanonnik.ttf);
👍

2017-10-30 16:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 16:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 17:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 17:40 UTC, Edheltur commented on css/pages/index.css
> +    text-align: justify;
👍

2017-10-30 17:42 UTC, Edheltur commented on css/pages/index.css
> +    column-count: 2;
👍

2017-10-30 17:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 17:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 17:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 18:15 UTC, Edheltur commented on css/blocks/main-visual.css
> +    left: calc(50% - 320px);
👍

2017-10-30 18:15 UTC, Edheltur commented on index.html
> +    </div>
👍

2017-10-30 18:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-30 19:30 UTC, Edheltur commented
🍏

2017-10-30 19:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 19:34 UTC, Edheltur commented
🍏

2017-10-31 06:19 UTC, Vittly commented on css/blocks/button.css
> +.btn
вообще лучше не лениться и писать полностью, тем более судя по имени блока - блок все-таки зовут `button`, а не `btn`

2017-10-31 06:21 UTC, Edheltur commented on css/blocks/button.css
> +.btn
btstrp stl

Уже раскопировал в следующую задачу этот класс. Поправлю.

2017-10-31 06:21 UTC, Vittly commented on css/blocks/button.css
> +}
и тут лучше делать модификаторы: `button_theme_red` и `button_width_large`

2017-10-31 06:22 UTC, Edheltur commented on css/blocks/button.css
> +}
опять же, с бутстрапа имена классов.

2017-10-31 06:23 UTC, Vittly commented on css/blocks/settings.css
> +    margin: 0 .3rem;
лучше сделать `margin` "вокруг", потому что на маленьких экранах, когда кнопки становятся в несколько строк, эти строики начинают примыкать друг к другу

2017-10-31 06:32 UTC, Vittly commented on css/blocks/settings.css
> +input[id='size-small']:checked ~ .settings label[for='size-small']
тут хочется какого-то более умного решения. Но более умного не придумал

2017-10-31 06:33 UTC, Vittly commented on css/blocks/settings.css
> +    display: inline;
а почему не `inline-block`?

2017-10-31 06:33 UTC, Vittly commented on css/blocks/button.css
> +
лишняя пустая строка и нужны вендор-префиксы

2017-10-31 06:34 UTC, Vittly commented on css/blocks/footer.css
> +.footer__description
не понял, почему тут `span`, а не `div`

2017-10-31 06:39 UTC, Vittly commented on css/blocks/main-visual.css
> +    font-size: 10rem;
[bug](https://yadi.sk/i/XIDAAfQ63PFbw4)

2017-10-31 06:44 UTC, Vittly commented on css/blocks/main-visual.css
> +    position: relative;
мне кажется, что лучше так (кстати, почему не назвать блок `header`?):

```html
<div class="main-visual__main-title">
    <div class="main-visual__date">...</div>
    <div class="main-visual__title">...</div>
</div>
```

2017-10-31 06:46 UTC, Vittly commented on css/blocks/main-visual.css
> +.main-visual__line
тогда лучше назвать `__group`, раз "строки" могут быть в одну строку

2017-10-31 06:46 UTC, Vittly commented on css/blocks/main-visual.css
> +        left: 31%;
всякие такие проценты надо сопровождать комментариями

2017-10-31 06:50 UTC, Vittly commented on css/pages/index.css
> +.date
мб использовать тег `time`

2017-10-31 06:50 UTC, Vittly commented on css/pages/index.css
> +.date
раз тут все про теги

2017-10-31 06:50 UTC, Vittly commented on css/pages/index.css
> +
лишняя пустая строка

2017-10-31 06:51 UTC, Vittly commented on css/pages/index.css
> +.date
или унести куда-то в другое место, раз это именно блок, потому что странно все даты/таймы на странице делать флоат-лефт

2017-10-31 06:51 UTC, Vittly commented on css/pages/index.css
> +    filter: contrast(200%) brightness(110%);
?

2017-10-31 06:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 06:54 UTC, Vittly commented on css/pages/index.css
> +    font-weight: bold;
я бы сделал без `float`/`text-indent` - а то выглядт странно. Вот будет у тебя первой буквой "В" и будет первых словом "вверх" и получится как будто орфографическая ошибка

2017-10-31 06:55 UTC, Vittly commented on css/blocks/button.css
> +.button-large
помоему модификаторы пишут или через `_` или через `--`

2017-10-31 06:55 UTC, Vittly commented on css/blocks/button.css
> +
пустая строка)

2017-10-31 06:57 UTC, Edheltur commented on css/blocks/button.css
> +
не очень смешно. тогда можно добавить эти правила в линтер в конце-концов. рядом с такими замечательными правилами.

```@font-face
{
    font-family: Chekhovskoy;
    src: url(../../fonts/chekhovskoy.woff2)
        format('woff2'), url(../../fonts/chekhovskoy.woff)
        format('woff'), url(../../fonts/chekhovskoy.ttf)
        format('truetype');
}

2017-10-31 07:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 07:02 UTC, Vittly commented on css/blocks/button.css
> +
убедил

2017-10-31 07:03 UTC, Vittly commented on css/blocks/main-visual.css
> +        /*Костыль. Подогнано на глаз. В 2017 году перепишите на флекс.*/
и еще бы уточнить, подогнано, чтобы "не наезжало на букву У" или типа того

2017-10-31 07:03 UTC, Vittly commented on css/pages/index.css
> +    display: inline;
а зачем тут `inline`? это точно надо?

2017-10-31 07:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 07:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 07:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 07:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 07:30 UTC, Edheltur commented
🍏

2017-10-31 07:34 UTC, Vittly commented
в целом все ок

2017-10-31 07:34 UTC, closed without merging