Смирнов Алексей
urfu-2017/markup-task-3 pull request #38
Opened 2017-10-23 04:37 UTC by AlexSm13

2017-10-23 04:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-23 04:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-23 17:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 08:27 UTC, nex2hex requested changes

2017-10-26 08:27 UTC, nex2hex commented on index.html
> +<html lang="en">
На маленьком разрешении текст теряется
https://yadi.sk/i/D39x82VC3P6Gq6

А на большом наоборот - https://yadi.sk/i/YseIDuuA3P7Dg6

Всегда следует указывать максимальные и минимальные границы у страницы (длинные строки текста читать тяжело)

2017-10-26 08:27 UTC, nex2hex commented on index.html
> +<html lang="en">
Текст отрывается от картинки https://yadi.sk/i/bcXVwIFT3P7DwU (решение легко гуглится)

2017-10-26 08:27 UTC, nex2hex commented on index.html
> +                    <p id="headd">NEW YORK</p>
в таких случаях наверно уместнее будет `<h3>`

2017-10-26 08:27 UTC, nex2hex commented
🍅

2017-10-28 18:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 12:47 UTC, nex2hex commented
🍏

2017-10-30 12:47 UTC, closed without merging