Первое решение.
urfu-2017/markup-task-3 pull request #50
Opened 2017-10-23 18:14 UTC by gus1234

Я не особо понимаю , что происходит при тексте без засечек и большом размере. Подскажете?

2017-10-23 18:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 04:11 UTC, gus1234 commented
Видимо, проблема зависит от браузера. С телефона у меня все ок.

2017-10-24 17:57 UTC, vaseker requested changes
В целом, хорошо, однако прошу правок.

2017-10-24 17:57 UTC, vaseker commented on index.css
> +    src: url(OldEnglishText.ttf);
у различных браузеров различные форматы поддерживаемых шрифтов (otf/woff/woff2/ttf, etc). стоит воспользоваться google fonts, чтобы избежать проблемы. нет гарантий, что Марти удастся прочесть такую газету

2017-10-24 17:57 UTC, vaseker commented on index.css
> +    font-size: 80%;
давай в относительных единицах `em` реализуем

2017-10-24 17:57 UTC, vaseker commented on index.css
> +    background-image: url('black_old_paper.jpg');
давай "состарим" фотки

2017-10-24 17:58 UTC, vaseker commented
🍅

2017-10-26 10:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 10:47 UTC, vaseker commented on index.css
> +    width: 100%;
к теме "состаривания": намек был на filter: grayscale(xx%), но ладно

2017-10-26 10:48 UTC, vaseker commented
🍏

2017-10-26 10:48 UTC, closed without merging