master
urfu-2017/markup-task-3 pull request #56
Opened 2017-10-23 20:11 UTC by Griboedoff

2017-10-23 20:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-23 20:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 14:38 UTC, Grimfrid commented on index.css
> +    src: url(./FiraCode-Regular.ttf);
`ttf` не всеми браузерами поддерживается, посмотри на caniuse другой формат

2017-10-26 14:44 UTC, Grimfrid requested changes
🍅

2017-10-27 15:49 UTC, Griboedoff commented on index.css
> +    src: url(./FiraCode-Regular.ttf);
![image](https://user-images.githubusercontent.com/16411561/32112900-06e7f8bc-bb58-11e7-9b43-f2476fe5645c.png)
не поддерживается в опере мини и частично в ИЕ, могу поменять на woff, но оперу мини уже ничего не спасет

2017-10-27 18:29 UTC, Grimfrid commented on index.css
> +    src: url(./FiraCode-Regular.ttf);
убедил)

2017-10-27 18:29 UTC, Grimfrid commented
🍏

2017-10-27 18:29 UTC, closed without merging