Муравьев Артем
urfu-2017/markup-task-3 pull request #60
Opened 2017-10-23 22:10 UTC by dreamzoul

2017-10-23 22:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 11:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 11:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 11:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 11:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 11:38 UTC, evilj0e requested changes
🍅

2017-10-24 11:38 UTC, evilj0e commented on index.html
> +                        Начнем с представления о Солнечной системе, так ли она выглядит, как учили в школе: в
Выровняй содержимое тега

2017-10-24 11:38 UTC, evilj0e commented on index.html
> +                        Давайте разберемся. Атмосферное давление открыто опытным путем физиком Еванджелиста
Поправь содержимое тега

2017-10-24 11:38 UTC, evilj0e commented on index.css
> +header.tittle
`title`

2017-10-24 11:38 UTC, evilj0e commented on index.css
> +    display: inline-grid;
Про гриды вам не рассказывали. Давай без них

2017-10-31 08:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-01 14:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-10 07:00 UTC, closed without merging