Не проверять
urfu-2017/markup-task-3 pull request #64
Opened 2017-10-23 23:31 UTC by Rolyx2

2017-10-23 23:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 11:55 UTC, Mokoshka requested changes
- Реши задачу без использования float. Вам пока про них не рассказывали, поэтому в этой задаче они не должны использоваться.
- Правая колонка улетает вниз страницы на маленьком экране
- В правой колонке не хватает отступов у фотографии
- в Firefox поехала верстка
![delorean dmc-12 2017-10-24 16-55-29](https://user-images.githubusercontent.com/14892550/31941698-26476a7c-b8dc-11e7-814c-94e7fea491a5.png)
- Шрифты очень маленькие

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    border: 1px solid black;
Давай использовать hex-код цвета

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    margin-left: 27%;
Почему в процентах?

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    padding-right: 10px;
`padding: 0 10px`?

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    padding-top: 35px;
`padding: 35px 15px 0`?

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    padding-right: 10px;
Здесь же тоже можно объединить?

2017-10-24 11:55 UTC, Mokoshka commented on index.css
> +    color: rgb(0, 128, 0);
Почему rgb?

2017-10-29 20:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 23:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 12:32 UTC, Mokoshka requested changes
1. Текст выходит за границы блока-контейнера 
![2017-11-03 16 43 13](https://user-images.githubusercontent.com/14892550/32373616-e94d7bce-c0bb-11e7-8c4b-d16c290932ca.png)
2. Хотелось бы, чтобы номер страницы был прибит к концу страницы. И было бы круто, чтобы колонка справа всегда растягивалась во всю высоту страницы
![image](https://user-images.githubusercontent.com/14892550/32373655-24ea321c-c0bc-11e7-90d8-b506edaa3604.png)
3. Увеличь шрифт, 10px для основного текста это очень мало. Давай хотя бы 16-17px.
4. Добавь семантичности в html, старайся избегать div, но не перестарайся
5. Слишком зафиксированы размеры странички, можно сделать более гибкой?
6. Для основного текста на странице ты используешь один и тот же шрифт и размер шрифта. Укажи его у body и переопределяй только там, где нужно.

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +p.asideText
Названия классов в верстке принято писать через дефиз: aside-text. Давай так перепишем все классы

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +    display: run-in;
Зачем?

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +.tes
Можно ли назвать класс более понятно? Сейчас из его названия не понятно зачем и к чему он относится

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +.redd
Две d?

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +.cent
Зачем сокращать?

2017-11-03 12:32 UTC, Mokoshka commented on index.css
> +.litl
Здесь тоже не зачем сокращать, кажется

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<main>
У head есть отступы, показывающие вложенность, а у body куда то они пропали. Сможешь вернуть и в последующих заданиях соблюдать их? Смотреть такой код, как сейчас очень сложно.

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<span class="grey top">НАКОРОТКЕ</span>
Давай у всех текстовых блоков, в которых весь текст написан заглавными буквами, укажем класс, у которого в стилях будет нужное преобразование текста.
Таким образом будет проще добавлять или убирать блоки с таким форматированием

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<img src="2.png" class="mainphoto" alt="">
Нехорошо оставлять alt пустым, да и title было бы неплохо указать

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<span class="grey bigText">ОЛЕ, «ЮВЕ!»</span><br>
Выглядит как заголовок

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<div class="aside">
Использование класса aside кажется намекает, что можно использовать что-то более семантичное, чем div

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<div class="leftSize"><img src="1.png" class="floatLeft photo" alt="Иллюстрация"></div>
floatLeft кажется лишний

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +<div class="leftSize"><img src="1.png" class="floatLeft photo" alt="Иллюстрация"></div>
alt совсем не информирует о том, что изображено на картинке. И title не хватает

2017-11-03 12:32 UTC, Mokoshka commented on index.html
> +    в еврокубки связано</div><div class="bold photoDescription">с нестабильным
Именно здесь разрешу использовать float

2017-12-11 12:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-11 13:19 UTC, Mokoshka approved these changes

2017-12-11 13:19 UTC, Mokoshka commented on index.css
> +    top: 20px;
На будущее. Такое позиционирование лучше делать с помощью margin-top.
Старайся избегать абсолютного позиционирования, с ним сложнее организовывать верстку

2017-12-11 13:19 UTC, closed without merging