^^
urfu-2017/markup-task-3 pull request #68
Opened 2017-10-24 00:56 UTC by iriskis

2017-10-24 00:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 19:07 UTC, msmirnov requested changes
🍅 

Почти ОК. Очень круто выглядят переключатели режимов.

- Не работает переключатель Serif/Sans Serif
- Хочется, чтобы какая-нибудь картинка занимала несколько колонок

2017-10-30 20:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 20:50 UTC, iriskis commented
Поправила  переключатель Serif/Sans Serif, установила картинку на несколько колонок, добавила footer  вместе с цитатой

2017-10-31 18:05 UTC, msmirnov approved these changes

2017-10-31 18:05 UTC, closed without merging