Тощилин Сергей
urfu-2017/markup-task-3 pull request #70
Opened 2017-10-24 03:00 UTC by spt30

[Посмотреть решение](https://rawgit.com/spt30/markup-task-3/master/index.html)

2017-10-24 03:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 08:12 UTC, evilj0e requested changes
🍅

2017-10-24 08:12 UTC, evilj0e commented on index.css
> +img[alt='Знак почета']
Завяжись лучше на класс.

2017-10-24 08:12 UTC, evilj0e commented on index.css
> +
Лишний перенос

2017-10-24 08:12 UTC, evilj0e commented on index.css
> +.podpis
Не используй транслит

2017-10-24 08:12 UTC, evilj0e commented on index.css
> +    font: bold 25pt serif;
У тебя везде разные единицы. Используй что-то одно.

2017-10-24 08:12 UTC, evilj0e commented on index.html
> +        <h1 class="present">С ПРАЗДНИКОМ РЕВОЛЮЦИИ, ЗЕМЛЯКИ!</h1>
Сделай написание текста заглавными буквами с помощью csц

2017-10-24 08:12 UTC, evilj0e commented on index.html
> +                        <div>
Найди более подходящие теги для этого случая: картинка и описание к ней

2017-10-24 08:12 UTC, evilj0e commented on index.html
> +                        <p>В. И. Ленин<br>— Задачи русских социал-демократов<br>(конец 1897 г.)</p>
Перед тире нельзя сделать перенос :(

2017-10-24 20:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-25 06:18 UTC, evilj0e approved these changes

2017-10-25 06:18 UTC, evilj0e commented
⭐️

2017-10-25 06:18 UTC, closed without merging