v1
urfu-2017/markup-task-3 pull request #71
Opened 2017-10-24 05:29 UTC by Naturin

2017-10-24 05:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 08:48 UTC, Mokoshka requested changes
1. Картинки не подгрузились
![delorean dmc-12 2017-10-30 13-48-03](https://user-images.githubusercontent.com/14892550/32161888-fc09977a-bd78-11e7-9328-3302e0acd080.png)

2. Было бы круто если бы заголовки не переносились
![delorean dmc-12 2017-10-30 13-46-35](https://user-images.githubusercontent.com/14892550/32161850-d3e4aa28-bd78-11e7-8965-5112c0d7ba02.png)

2017-10-30 08:48 UTC, Mokoshka commented on index.css
> +    display: flex;
Так как про flex вам еще не рассказывали, то и использовать их пока что нельзя. Будет отдельная домашка на использование flex.
Давай сверстаем без использования flex

2017-10-30 08:48 UTC, Mokoshka commented on index.html
> +                    <strong>Пи&shy;та&shy;ние.</strong>Уче&shy;ные до&shy;ка&shy;за&shy;ли,
Эффект от этого элемента в Chrome потерялся
![delorean dmc-12 2017-10-30 13-42-31](https://user-images.githubusercontent.com/14892550/32161672-4e3df582-bd78-11e7-9ab6-3c1b96f32901.png)

2017-11-02 18:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 12:45 UTC, Mokoshka requested changes
Чуть-чуть поправить и приму

2017-11-03 12:45 UTC, Mokoshka commented on index.css
> +.release_date
Принято указывать названия классов через дефиз: release-date

2017-11-03 12:45 UTC, Mokoshka commented on index.css
> +    display: inline-block;
Зачем делать их inline блоками?

2017-11-03 13:12 UTC, Naturin commented on index.css
> +    display: inline-block;
чтобы заголовки не переносились по частям, это было замечание выше

2017-11-03 13:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 13:35 UTC, Mokoshka commented on index.css
> +    display: inline-block;
Это неправильное решение проблемы. Правильно будет использовать здесь break-inside

2017-11-03 13:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-03 20:26 UTC, Mokoshka approved these changes

2017-11-03 20:26 UTC, closed without merging