Котельников Алексей
urfu-2017/markup-task-3 pull request #73
Opened 2017-10-24 07:52 UTC by NameOff

2017-10-24 07:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 07:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 08:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-24 08:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 08:37 UTC, nex2hex requested changes
🍅

2017-10-26 08:37 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
Не задана минимальная и максимальная ширина текста https://yadi.sk/i/ZxUt_S0k3P7Eqh

2017-10-26 08:37 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
Переносится подпись к картинке (решение гуглится) https://yadi.sk/i/OaGE8Jel3P7Exh

2017-10-26 08:37 UTC, nex2hex commented on index.html
> +                    Рус<wbr>лан Со<wbr>ко<wbr>лов<wbr>ский по<wbr>сле по
на странице должен быть только один `<h1>`

2017-10-26 08:37 UTC, nex2hex commented on index.html
> +                ЛОВЕЦ ПОКЕМОНОВ СНОВА В СИЗО?
текст надо писать как в книгах маленькими буквами. Такие трансформации делаются на css

2017-10-26 08:37 UTC, nex2hex commented on index.html
> +                <div class="comment">
`figcaption`

2017-10-26 08:37 UTC, nex2hex commented on index.css
> +@font-face
`@font-face` лучше указывать в начале файла

2017-10-26 08:37 UTC, nex2hex commented on index.css
> +    font: italic 16px President, 'Times New Roman';
лучше `em`
https://stackoverflow.com/questions/609517/why-em-instead-of-px
https://css-tricks.com/why-ems/

2017-10-26 08:37 UTC, nex2hex commented on index.css
> +    text-align: justify;
для газеты - ок, но в реальной жизни никогда не используй этот тэг. браузеры растягивают строку только между словами и текст становится тяжело читать

2017-10-28 16:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-28 16:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 13:06 UTC, nex2hex requested changes
:tomato:

2017-10-30 13:06 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
https://yadi.sk/i/TTw1z8fo3PEDvM
По-умолчанию на больших мониторах контент должен быть по центру экрана 
Пример - vk.com meduza.io

2017-10-30 13:06 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
https://yadi.sk/i/ctwH9vNs3PEEtm
В газетах картинки выровнены на всю ширину абзаца

2017-10-30 13:06 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
Картинка по прежнему переносится https://yadi.sk/i/tiPlMFsf3PEFja

2017-10-30 13:06 UTC, nex2hex commented on index.html
>  <!DOCTYPE html>
https://stackoverflow.com/questions/8506783/css3-columns-force-non-breaking-splitting-element

2017-10-30 19:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 06:53 UTC, nex2hex commented
🍏

2017-10-31 06:53 UTC, closed without merging