газета
urfu-2017/markup-task-3 pull request #74
Opened 2017-10-24 08:01 UTC by HazipovVF

2017-10-24 08:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 19:22 UTC, msmirnov requested changes
🍅 

При ширине < 1450px правая колонка уезжает вниз.

Не хватает:

- цитат
- картинок
- подписей к картинкам
- хотелось бы, чтобы какая-нибудь картинка занимала несколько колонок

2017-10-24 19:22 UTC, msmirnov commented on index.css
> +.twoColumns
Названия классов обычно пишутся не через [camelCase](https://ru.wikipedia.org/wiki/CamelCase), а через [kebab-case](https://ru.wikipedia.org/wiki/Snake_case)

2017-10-24 19:22 UTC, msmirnov commented on index.html
> +            <div class="twoColumns">
Не хватает семантики. Я бы для блоков `twoColumns` и `threeColumns` использовал тег `article`.

2017-10-26 17:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-27 10:09 UTC, closed without merging