Задание 3 готово
urfu-2017/markup-task-3 pull request #78
Opened 2017-10-24 09:10 UTC by RomanDengin

Дополнительное задание не делал

2017-10-24 09:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-26 05:01 UTC, savichev-igor requested changes
Газета хоть и выглядит приятно, но соблюдены не все особенности вёрстки того времени

А ещё как мне кажется колонка как-то странно уезжает правая
![image](https://user-images.githubusercontent.com/7279995/32035711-6ceb30e0-ba34-11e7-9721-4af2603b2c67.png)

🍅

2017-10-26 05:01 UTC, Savichev-Igor commented on index.css
> +    src: url('fonts/Carmen.ttf');
Я бы ещё проверял, есть ли у пользователя уже этот шрифт с помощью `local`

2017-10-26 05:01 UTC, Savichev-Igor commented on index.css
> +    src: url('fonts/Carmen.ttf');
И не ограничивался одним лишь форматом

2017-10-26 05:01 UTC, Savichev-Igor commented on index.css
> +    float: left;
К сожалению, `float` в этой задаче использовать нельзя, так как про него ещё не рассказывали :<

2017-10-26 05:01 UTC, Savichev-Igor commented on index.html
> +    <div class="topnews">
Практически любой `div` можно заменить на более семантический тэг - уж тут точно

2017-10-26 05:01 UTC, Savichev-Igor commented on index.css
> +    column-count: 3;
Добавь вендорных префиксов, не у всех последние версии браузеров

2017-10-31 08:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 08:53 UTC, RomanDengin commented
🍏 
поправил замечания

2017-10-31 09:43 UTC, Savichev-Igor commented on index.css
> +    src: local('Carmen'), url('fonts/Carmen.ttf');
Я бы ещё формат указывал

2017-10-31 09:43 UTC, Savichev-Igor commented on index.css
> +    padding: 10px;
`padding: 10px 10px 10px 20px;`

Хоть и громоздко, но в одну строку

2017-10-31 09:44 UTC, Savichev-Igor commented on index.css
> +    column-rule: 1px black solid;
Сначала вендорные правила, потом браузерные

2017-10-31 10:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 10:57 UTC, Savichev-Igor commented
⭐️

2017-10-31 10:57 UTC, savichev-igor approved these changes

2017-10-31 10:58 UTC, closed without merging