Левшин Михаил
urfu-2017/markup-task-3 pull request #8
Opened 2017-10-19 14:05 UTC by LevshinMisha

2017-10-19 14:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 05:47 UTC, f0rmat1k requested changes
— Не критично, но вид газеты так себе. Может попробуешь найти паттерн какой-нибудь старой бумаги на фон? Я не почувствовал теплой ламповости.
— В задании явно не указано, но все абзацы должны начинаться с небольшого отступа. Это можно заметить в примерах.
— Почему у внутренних заголовков отступ снизу больше, чем сверху.
— В словах нет переносов.
— В меню экстра-задания непонятно, что сейчас выбрано.

2017-10-20 05:47 UTC, f0rmat1k commented on index.html
> +                <img alt="маленький котенок" src="cat.jpeg">
А где сама картинка?

2017-10-20 05:47 UTC, f0rmat1k commented on index.html
> +            <div class="pic">
Для группировки картинки и подписи есть намного более подходящий тег.

2017-10-20 21:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 22:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 22:24 UTC, LevshinMisha commented
Переносы делал с помощью сервиса из лекций http://quittance.ru/hyphenator.php

2017-10-21 07:21 UTC, closed without merging