first commit
urfu-2017/markup-task-3 pull request #80
Opened 2017-10-24 10:21 UTC by HEXBATAET

2017-10-24 10:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 11:07 UTC, mokhov requested changes
Нет подписей к картинкам, в остальном отличная работа 👍 
🍅

2017-10-30 12:01 UTC, HEXBATAET commented
подписей, ты имеешь в виду title у тэга img? Вообще, есть вопрос по поводу атрибута align у img. Что с ним не так и почему линтер ругается на его использование?

2017-10-30 13:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-02 04:34 UTC, closed without merging