Мальцев Илья
urfu-2017/markup-task-3 pull request #83
Opened 2017-10-24 11:42 UTC by Maidoo1

2017-10-24 11:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-25 13:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-25 14:01 UTC, vaseker requested changes

2017-10-25 14:01 UTC, vaseker commented on index.css
> +    height: 1px;
рамки нужно сделать на псевдоэлементах

2017-10-25 14:01 UTC, vaseker commented on index.css
> +.inline > div
.inline-блок - это вообще жесть. стандартно 3 колонки верстают так:
{ float:left; }
{ float:right; }
{ margin: 0 auto; }

2017-10-25 14:01 UTC, vaseker commented
🍅

2017-10-26 14:52 UTC, Maidoo1 commented on index.css
> +    height: 1px;
Я не очень умный, как сделать рамки на псевдоэлементах?
Что-то типа img:after {border-bottom: ...} ?

2017-10-26 15:05 UTC, vaseker commented on index.css
> +    height: 1px;
Да, типа того, добавив еще content:'' для отображения и position:absolute для выравнивания

2017-10-26 15:18 UTC, Maidoo1 commented on index.css
> +    height: 1px;
Спасибо

2017-10-26 21:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-27 09:12 UTC, vaseker commented on index.css
> +input[id='cellblock']:checked ~ div h1,
#cellblock

2017-10-27 09:15 UTC, vaseker commented
🍏 
![my-eyes](https://user-images.githubusercontent.com/1942271/32096886-36b421ba-bb21-11e7-8cab-cf5e99dbb41c.jpg)

2017-10-27 09:15 UTC, closed without merging