Евдокимов Илья
urfu-2017/markup-task-3 pull request #88
Opened 2017-10-26 13:16 UTC by maffas

2017-10-26 13:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 13:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 13:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 13:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 13:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-26 13:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 11:09 UTC, mokhov requested changes
Колонок так и не получилось 🍅 
![delorean dmc-12 2017-10-30 14-07-54](https://user-images.githubusercontent.com/357689/32168005-eb4445a4-bd7b-11e7-8852-49e09b8c00c7.png)

2017-10-30 11:09 UTC, mokhov commented on index.css
> +    background-color: rgb(0, 0, 0);
Этот цвет можно записать короче

2017-10-30 11:09 UTC, mokhov commented on index.css
> +    margin: -1px;
Зачем нужно это правило?

2017-10-30 11:09 UTC, mokhov commented on index.html
> +                <div></div>
Зачем нужен этот элемент?

2017-10-31 06:08 UTC, maffas commented on index.html
> +                <div></div>
остатки от былой роскоши

2017-10-31 06:11 UTC, maffas commented on index.css
> +    margin: -1px;
![default](https://user-images.githubusercontent.com/32200778/32209833-2815fe40-be2c-11e7-9c25-e677ed4a3a3c.PNG)
прятал белую рамку

2017-10-31 06:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 06:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 06:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-02 04:32 UTC, mokhov commented
Увеличенный шрифт не увеличивает заголовки и ломает прежние колонки
![delorean dmc-12 2017-11-02 07-31-50](https://user-images.githubusercontent.com/357689/32309938-ffa55288-bf9f-11e7-8711-4f67e5483d80.png)
![delorean dmc-12 2017-11-02 07-31-59](https://user-images.githubusercontent.com/357689/32309936-fef66502-bf9f-11e7-9e79-eac7ca06c852.png)

2017-11-02 04:33 UTC, mokhov commented on index.css
> +    margin: -1px;
Кажется это лечение искуственно созданных проблем

2017-11-02 04:33 UTC, mokhov commented on index.html
> +                <div></div>
Не понятно

2017-11-02 17:53 UTC, maffas commented
Возможно я изначально некорректно понял задание, и я стремился именно к тому чтобы количество столбцов регулировалось от размера текста и окна.

2017-11-02 18:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-02 18:05 UTC, maffas commented on index.html
> +                <div></div>
когда я только начинал делать я видимо совсем не подумал о  display: flex и хотел поставить пустые блоки(очень глупо хотел поступить).

2017-11-02 18:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-05 09:04 UTC, closed without merging