1
urfu-2017/markup-task-3 pull request #9
Opened 2017-10-20 15:22 UTC by Morkhod

2017-10-20 15:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-20 15:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 08:49 UTC, savichev-igor requested changes
В целом ок, но

1) Ещё я бы попробовал сделать картинку с подписью к ней на несколько колонок, как в условии задачи

2) Добавил отступы от краёв, а то читать крайне сложно, когда текст на стыке двух цветов

3) Добавил вендорных префиксов на `css` свойства, которые требуют того, ибо вдруг кто-то откроет в более старых версиях браузера, где ещё нет из коробки

🍅

2017-10-21 08:49 UTC, savichev-igor commented on index.css
> +    float: left;
Кажется, что плавающие элементы в этой задаче использовать нельзя

2017-10-21 08:49 UTC, savichev-igor commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic"
Давай ещё попробуем самостоятельно подключить шрифт какой-нибудь, без использования внешних ресурсов

2017-10-21 08:49 UTC, savichev-igor commented on index.html
> +    <input type="radio" id="size_0.8" name="size">
А почему `input` внутрь `label` не вставишь?

2017-10-21 08:49 UTC, savichev-igor commented on index.html
> +    <input type="checkbox" id="theme_color_dark" name="theme_color">
Как-то по-разному пишешь `name` для инпутов: где-то через `_`, где-то через `-`

2017-10-22 19:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-22 19:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-22 19:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-22 19:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 19:13 UTC, Morkhod commented
Насчет input в label - насколько я знаю нет отношения родителя в css и как написать селектор я не в курсе.

2017-10-22 19:14 UTC, Morkhod commented
А насчет префиксов - я в курсе такой возможности,просто не знаю где уместно будет их вставлять,а где нет.

2017-10-23 10:11 UTC, savichev-igor requested changes
Про использование кастомных свойств и их поддержку можно читать на http://caniuse.com/

А про `input` в `label` - браузер сам поймёт при клике на `label`, что нужно изменить `input`, лежащий в нём

И ещё, я так и не увидел картинки сразу на две колонки

🍅

2017-10-23 10:11 UTC, Savichev-Igor commented on index.css
> +    src: url('Typingrad.ttf') format('ttf');
Я бы старался использовать все имеющиеся форматы и подключать их в порядке распространения поддержки, вам должны были это в лекции рассказывать на сколько я помню

А ещё бы указал `local`

2017-10-23 10:11 UTC, Savichev-Igor commented on index.css
> +.colspanimg
Ужасное название класса)

2017-10-23 16:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-23 16:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 06:57 UTC, savichev-igor approved these changes

2017-10-24 06:57 UTC, Savichev-Igor commented
⭐️

2017-10-24 06:57 UTC, Savichev-Igor commented
⭐️

2017-10-24 06:57 UTC, closed without merging